/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_DASH_DASH_DASH = 1,
  anon_sym_LF = 2,
  anon_sym_COLON = 3,
  anon_sym_SPACE = 4,
  sym_field_name = 5,
  aux_sym_field_value_token1 = 6,
  aux_sym_body_token1 = 7,
  sym_source_file = 8,
  sym_front_matter = 9,
  sym_delimiter = 10,
  sym_field = 11,
  sym_field_value = 12,
  sym_body = 13,
  aux_sym_front_matter_repeat1 = 14,
  aux_sym_body_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_LF] = "\n",
  [anon_sym_COLON] = ":",
  [anon_sym_SPACE] = " ",
  [sym_field_name] = "field_name",
  [aux_sym_field_value_token1] = "field_value_token1",
  [aux_sym_body_token1] = "body_token1",
  [sym_source_file] = "source_file",
  [sym_front_matter] = "front_matter",
  [sym_delimiter] = "delimiter",
  [sym_field] = "field",
  [sym_field_value] = "field_value",
  [sym_body] = "body",
  [aux_sym_front_matter_repeat1] = "front_matter_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_field_name] = sym_field_name,
  [aux_sym_field_value_token1] = aux_sym_field_value_token1,
  [aux_sym_body_token1] = aux_sym_body_token1,
  [sym_source_file] = sym_source_file,
  [sym_front_matter] = sym_front_matter,
  [sym_delimiter] = sym_delimiter,
  [sym_field] = sym_field,
  [sym_field_value] = sym_field_value,
  [sym_body] = sym_body,
  [aux_sym_front_matter_repeat1] = aux_sym_front_matter_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_field_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_front_matter] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_front_matter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(2);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_field_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_field_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_body_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [sym_field_name] = ACTIONS(1),
    [aux_sym_body_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_front_matter] = STATE(3),
    [sym_delimiter] = STATE(2),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(7), 1,
      sym_field_name,
    STATE(8), 1,
      sym_delimiter,
    STATE(4), 2,
      sym_field,
      aux_sym_front_matter_repeat1,
  [14] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_body_repeat1,
    STATE(17), 1,
      sym_body,
    ACTIONS(11), 2,
      aux_sym_field_value_token1,
      aux_sym_body_token1,
  [28] = 4,
    ACTIONS(5), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(7), 1,
      sym_field_name,
    STATE(9), 1,
      sym_delimiter,
    STATE(7), 2,
      sym_field,
      aux_sym_front_matter_repeat1,
  [42] = 3,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_body_repeat1,
    ACTIONS(15), 2,
      aux_sym_field_value_token1,
      aux_sym_body_token1,
  [53] = 3,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_body_repeat1,
    ACTIONS(19), 2,
      aux_sym_field_value_token1,
      aux_sym_body_token1,
  [64] = 3,
    ACTIONS(22), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(24), 1,
      sym_field_name,
    STATE(7), 2,
      sym_field,
      aux_sym_front_matter_repeat1,
  [75] = 1,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      aux_sym_field_value_token1,
      aux_sym_body_token1,
  [81] = 1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      aux_sym_field_value_token1,
      aux_sym_body_token1,
  [87] = 1,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      aux_sym_field_value_token1,
      aux_sym_body_token1,
  [93] = 1,
    ACTIONS(31), 2,
      anon_sym_DASH_DASH_DASH,
      sym_field_name,
  [98] = 2,
    ACTIONS(33), 1,
      anon_sym_LF,
    ACTIONS(35), 1,
      anon_sym_SPACE,
  [105] = 1,
    ACTIONS(37), 2,
      anon_sym_DASH_DASH_DASH,
      sym_field_name,
  [110] = 2,
    ACTIONS(39), 1,
      aux_sym_field_value_token1,
    STATE(21), 1,
      sym_field_value,
  [117] = 1,
    ACTIONS(41), 2,
      anon_sym_DASH_DASH_DASH,
      sym_field_name,
  [122] = 1,
    ACTIONS(43), 1,
      anon_sym_LF,
  [126] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [130] = 1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
  [134] = 1,
    ACTIONS(49), 1,
      anon_sym_COLON,
  [138] = 1,
    ACTIONS(51), 1,
      anon_sym_LF,
  [142] = 1,
    ACTIONS(53), 1,
      anon_sym_LF,
  [146] = 1,
    ACTIONS(55), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 53,
  [SMALL_STATE(7)] = 64,
  [SMALL_STATE(8)] = 75,
  [SMALL_STATE(9)] = 81,
  [SMALL_STATE(10)] = 87,
  [SMALL_STATE(11)] = 93,
  [SMALL_STATE(12)] = 98,
  [SMALL_STATE(13)] = 105,
  [SMALL_STATE(14)] = 110,
  [SMALL_STATE(15)] = 117,
  [SMALL_STATE(16)] = 122,
  [SMALL_STATE(17)] = 126,
  [SMALL_STATE(18)] = 130,
  [SMALL_STATE(19)] = 134,
  [SMALL_STATE(20)] = 138,
  [SMALL_STATE(21)] = 142,
  [SMALL_STATE(22)] = 146,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_front_matter_repeat1, 2, 0, 0),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_front_matter_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_front_matter, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_front_matter, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimiter, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_value, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_snapshot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "snapshot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
