/**
 * @file Snapshot test files generated by Shutter
 * @author ptdewey
 * @license MIT
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "snapshot",

  rules: {
    // TODO: add the actual grammar rules
    source_file: $ => "hello"
  }
});
